Terraform aws release
LewisAlvarez/Mono-Repo-Devops pull request #8
Opened 2020-10-24 16:06 UTC by LewisAlvarez

2020-10-24 17:38 UTC, juanfe2793 requested changes

2020-10-24 17:38 UTC, juanfe2793 commented on Infra/conf_Terraform/main.tf
> +    #Credenciales de la cuenta
Borren esto. Información sensible. Los access key y los secrets se manejan localmente.

2020-10-24 17:38 UTC, juanfe2793 commented on Infra/conf_Terraform/main.tf
>      }
El security group debería incluir también el puerto de la aplicación. 3030 o 3000, el que utilizan.

2020-10-24 17:38 UTC, juanfe2793 commented on Infra/conf_Terraform/main.tf
> +    availability_zones = []"${data.aws_availability_zones.all_zones.names}"]
Quitar
[ **]**"${data.aws_availability_zones.all_zones.names}"]

2020-10-24 17:38 UTC, juanfe2793 commented on Infra/conf_Terraform/main.tf
> -resource "docker_image" "image_backEnd"{
En general no entiendo la idea del Docker, porque siguen manejando todo con docker??

2020-10-24 17:38 UTC, juanfe2793 commented on Infra/conf_Terraform/terraform.tfvars
> +my_access_key = "aws_user_access_key"
Borrar

2020-10-24 17:38 UTC, juanfe2793 commented on Infra/conf_Terraform/variables.tf
> +    default = "2"
lo pueden dejar en 1 mientras tanto.

2020-10-28 22:09 UTC, LewisAlvarez commented on Infra/conf_Terraform/main.tf
> -resource "docker_image" "image_backEnd"{
No entiendo por qué en el PR aparecen cosas de docker si en el archivo no aparece nada de eso.

2020-10-28 22:11 UTC, LewisAlvarez commented on Infra/conf_Terraform/variables.tf
> +    default = "2"
Hecho¡

2020-10-28 22:11 UTC, LewisAlvarez commented on Infra/conf_Terraform/terraform.tfvars
> +my_access_key = "aws_user_access_key"
Hecho

2020-10-28 22:11 UTC, LewisAlvarez commented on Infra/conf_Terraform/main.tf
> +    #Credenciales de la cuenta
Hecho

2020-10-28 22:14 UTC, LewisAlvarez commented on Infra/conf_Terraform/main.tf
>      }
Hecho

2020-11-05 17:35 UTC, juanfe2793 approved these changes

2020-11-05 17:35 UTC, juanfe2793 commented
lgtm, solve conflicts and merge

2020-11-05 18:13 UTC, closed without merging